apiVersion: v1
kind: Service
metadata:
  name: main
  namespace: namespace-workflow-1693722624174
spec:
  type: LoadBalancer
  selector:
    app: main
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000